apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: pizza-apiserver
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 31443
  selector:
    apiserver: "true"
  type: NodePort
