apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.restaurant.chanshik.dev
spec:
  insecureSkipTLSVerify: true
  group: restaurant.chanshik.dev
  groupPriorityMinimum: 1000
  versionPriority: 20
  service:
    name: api
    namespace: pizza-apiserver
  version: v1beta1
